version: '3.7'

x-hidmanbase: &hidman-base

    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_SRC: python:3.8

    volumes:
      - type: bind
        source: ./
        target: /usr/local/src/hidman

    image: iitschri/hidman:latest

    privileged: true
    stdin_open: true
    tty: true
    network_mode: host

services:

  hidman-serv:
    <<: *hidman-base
    devices:
      - /dev/input/by-id/usb-MicroPython_Pyboard_Virtual_Comm_Port_in_FS_Mode_206B349A344D-event-kbd:/dev/input/pyboard
    command: python3 hidman/tests/02_server.py

  hidman-client:
    <<: *hidman-base
    command: python3 hidman/tests/02_client.py
    depends_on:
      - hidman-serv
